name: Reminder CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          poetry install

      # - name: Run Linter (pylint)
      #   run: |
      #     pylint reminder/**/*.py

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        run: |
          pytest reminder/test/

  # docker:
  #   name: Build Docker Images
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log in to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and Push API Image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/reminder-api -f reminder/Dockerfile .
  #         docker push ${{ secrets.DOCKER_USERNAME }}/reminder-api

  #     - name: Build and Push Nginx Image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/reminder-nginx -f reminder_nginx/Dockerfile .
  #         docker push ${{ secrets.DOCKER_USERNAME }}/reminder-nginx
